version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - '27017:27017'
      
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quotr-_container
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
